// Sytelens — mock verdict data for Step 2 (UI before the backend exists).
// Shape matches the DynamoDB record / Lambda response in SYTELENS_BRIEF.md.
// Replaced by live API data in the wiring step (Step 8).

import { T } from "./theme.js";

export const SCENARIOS = {
  green: {
    domain: "microsoft.com",
    favicon: "M",
    faviconColor: "#00a4ef",
    score: 94,
    verdict: "SAFE",
    state: "green",
    color: T.green,
    bg: T.greenBg,
    cached: true,
    cachedAgo: "12 days ago",
    summary: "Large established corporation with transparent business practices, long domain history, and no deceptive patterns.",
    domainAge: "29 years",
    registrar: "MarkMonitor Inc.",
    hosting: "Microsoft Azure, Redmond WA",
    https: true,
    whatItIs: [
      "Enterprise software and cloud services company",
      "Publicly traded on NASDAQ (MSFT) — SEC filings publicly accessible",
      "Revenue model: subscriptions, licensing, cloud consumption",
      "Pricing fully disclosed — no hidden funnel",
      "Physical HQ: One Microsoft Way, Redmond WA",
    ],
    urlParams: [],
    redFlags: [],
    greenSignals: [
      "Domain registered 1991 — 29 years of history",
      "Publicly traded company with SEC filings",
      "Pricing fully disclosed on site",
      "No ad tracking parameters in URL",
      "Clear operator identity and physical address",
      "SSL certificate issued to Microsoft Corporation",
    ],
  },
  yellow: {
    domain: "getfractionalfreedom.com",
    favicon: "F",
    faviconColor: "#8B5CF6",
    score: 52,
    verdict: "CAUTION",
    state: "yellow",
    color: T.amber,
    bg: T.amberBg,
    cached: false,
    cachedAgo: null,
    summary: "Legitimate consulting course business, but uses aggressive ad funnels, lacks pricing transparency, and operator identity is partially obscured.",
    domainAge: "~2 years",
    registrar: "GoDaddy",
    hosting: "Leadpages / AWS",
    https: true,
    whatItIs: [
      "Paid course teaching experts how to become a fractional/consulting business owner",
      "Operated by \"Laura\" — full name not prominently disclosed (JoyBrand Creative)",
      "Built on Instagram paid ads — 6 Meta tracking parameters in this URL",
      "Testimonials cite \"$10K/month consulting clients\" — cherry-picked, not averages",
      "\"AI\" branding appears to be a 2024–2025 rebrand of an existing course, not a new product",
    ],
    urlParams: [
      { key: "fbc_id", note: "Facebook click ID" },
      { key: "utm_source", value: "ig", note: "Instagram paid" },
      { key: "utm_medium", value: "paid", note: "Paid media" },
      { key: "utm_campaign", note: "Campaign tracking" },
      { key: "utm_content", note: "Ad creative tracking" },
      { key: "fbclid", note: "Facebook click attribution" },
    ],
    redFlags: [
      "No pricing visible without clicking through the funnel",
      "\"Laura\" — no full name prominently shown on the main page",
      "\"AI\" grafted onto existing consulting course — marketing move, not a substantive change",
    ],
    greenSignals: [
      "Real domain with 2+ year history",
      "HTTPS with valid SSL certificate",
      "Identified operator — JoyBrand Creative",
      "No malware or phishing signals",
      "Vimeo-hosted video (not fake testimonial deepfake)",
    ],
  },
  red: {
    domain: "ai-profit-returns-daily.com",
    favicon: "!",
    faviconColor: "#EF4444",
    score: 8,
    verdict: "HIGH RISK",
    state: "red",
    color: T.red,
    bg: T.redBg,
    cached: false,
    cachedAgo: null,
    summary: "Strong scam indicators. Newly registered domain, no identifiable operator, guaranteed return claims, and known phishing pattern signatures.",
    domainAge: "23 days",
    registrar: "Namecheap (privacy-shielded)",
    hosting: "Cloudflare proxy — origin unknown",
    https: true,
    whatItIs: [
      "Claims AI-powered investment returns of $3,000/day — no mechanism explained",
      "No registered business entity, no verifiable principals",
      "Affiliate tracking params (aff_id) suggest pay-per-victim referral model",
      "No regulatory disclosures — SEC, FINRA, or FCA registration absent",
      "HTTPS present but meaningless — scammers use it routinely",
    ],
    urlParams: [
      { key: "ref", note: "Referral tracking" },
      { key: "aff_id", note: "Affiliate ID — pay-per-victim model" },
      { key: "lp", note: "Landing page variant" },
    ],
    redFlags: [
      "Domain registered 23 days ago",
      "Registrant identity hidden behind privacy shield",
      "Guaranteed return claims ($3,000/day) — illegal in most jurisdictions",
      "No operator name, address, or business registration",
      "Affiliate tracking params suggest pay-per-victim referral model",
      "No regulatory disclosures (SEC, FINRA, FCA)",
      "Hosting origin masked by Cloudflare proxy",
      "Deepfake video testimonials detected",
    ],
    greenSignals: [
      "HTTPS present (not meaningful for trust at this risk level)",
    ],
  },
};
